export { default as Home } from './home'
export { default as Login } from './login'
export { default as Signup } from './signup'
export { default as ForumPage } from './forum'
export { default as ForumDetailById } from './forum/id'
export { default as ForumCreatePage } from './forum/create'
export { default as NotFoundPage } from './not-found'
